<?php

if (!defined('GDY_ADMIN_BOOT')) {
  header('Location: index.php?tab=theme');
  exit;
}

if (!function_exists('h')) {
  function h($s){ return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }
}

$__gdy_root = null;
if (defined('GODYAR_ROOT') && gdy_is_dir((string) GODYAR_ROOT) === true) {
  $__gdy_root = rtrim(GODYAR_ROOT, '/');
} else {
  
  $__gdy_root = realpath(__DIR__ . '/../../');
  $__gdy_root = $__gdy_root ? rtrim(str_replace('\\','/',$__gdy_root), '/') : null;
}
$__cfg_file = ($__gdy_root ? $__gdy_root . '/storage/config/site_theme.php' : null);

$themes_dir = ($__gdy_root ? $__gdy_root . '/assets/css/themes' : null);
$themes = [];
if ($themes_dir && gdy_is_dir($themes_dir) === true) {
  foreach (glob($themes_dir . '/theme-*.css') as $f) {
    $rel = 'assets/css/themes/' . basename($f);
    $themes[] = $rel;
  }
}
sort($themes);

$__current = null;
if (function_exists('site_settings_get')) {
  $__current = site_settings_get('frontend_theme', null);
  if (!$__current) $__current = site_settings_get('front_theme', null);
  if (!$__current) $__current = site_settings_get('site_theme', null);
  if (!$__current) {
    $preset = site_settings_get('front_preset', null);
    if ($preset) $__current = (strpos($preset, 'theme-') === 0) ? "assets/css/themes/{$preset}.css" : "assets/css/themes/theme-{$preset}.css";
  }
}
if ((!$__current) && $__cfg_file && gdy_is_file($__cfg_file) === true) {
  $__current = @include $__cfg_file;
}
if (!$__current) $__current = 'assets/css/themes/theme-blue.css';

if ($themes && !in_array($__current, $themes, true)) {
  
  $tmp = (string)$__current;
  $tmp = preg_replace('~^https?://[^/]+/~i', '', $tmp);
  $tmp = ltrim($tmp, '/');
  if (in_array($tmp, $themes, true)) $__current = $tmp;
}

$flash_ok = false;
$flash_err = null;

if (gdy_request_method() === 'POST') {
  $sel = trim(gdy_post_var('site_theme', ''));
  
  if ($sel === '') $sel = trim(gdy_post_var('frontend_theme', ''));
  if ($sel === '') $sel = trim(gdy_post_var('front_theme', ''));

  
  $sel = preg_replace('~^https?://[^/]+/~i', '', $sel);
  $sel = ltrim($sel, '/');

  if ($themes && !in_array($sel, $themes, true)) {
    $flash_err = 'الثيم المحدد غير صالح.';
  } else {
    
    if (function_exists('site_settings_set') && isset($pdo) && $pdo) {
      site_settings_set($pdo, 'site_theme', $sel);
      site_settings_set($pdo, 'front_theme', $sel);
      site_settings_set($pdo, 'frontend_theme', $sel);

      
      $slug = 'blue';
      if (preg_match('~theme-([a-z0-9_-]+)\.css$~i', $sel, $m)) $slug = strtolower($m[1]);
      site_settings_set($pdo, 'front_preset', $slug);
    }

    
    if ($__cfg_file) {
      $dir = gdy_dirname($__cfg_file);
      if (gdy_is_dir($dir) === false) { gdy_mkdir($dir, 0755, true); }
      $php = "<?php\n// Auto-generated by Admin > Settings > Theme\nreturn '" . addslashes($sel) . "';\n";
      gdy_file_put_contents($__cfg_file, $php, LOCK_EX);
    }

    $__current = $sel;
    $flash_ok = true;
  }
}

?>
<div class="gdy-admin-container">
  <div class="gdy-page-header">
    <h1 class="gdy-page-title h4 mb-2">المظهر</h1>
    <div class="text-muted">اختيار ثيم الواجهة من مجلد <code>/assets/css/themes</code></div>
  </div>

  <?php if ($flash_ok): ?>
    <div class="alert alert-success">تم الحفظ</div>
  <?php elseif ($flash_err): ?>
    <div class="alert alert-danger"><?php echo h($flash_err); ?></div>
  <?php endif; ?>

  <div class="card" style="max-width:980px;background:var(--gdy-surface-2);border:1px solid var(--gdy-border);">
    <div class="card-body">
      <form method="post" action="">
        <?php if (function_exists('csrf_field')) { echo csrf_field(); } ?>

        <div class="mb-3">
          <label class="form-label">الثيم الحالي</label>
          <div class="d-flex flex-wrap gap-2 align-items-center">
            <span class="badge text-bg-primary" style="font-size:.9rem;"><?php echo h($__current); ?></span>
            <span class="text-muted" style="font-size:.9rem;">اختر ثيم من القائمة ثم احفظ.</span>
          </div>
        </div>

        <div class="mb-3">
          <label class="form-label">قائمة الثيمات المتاحة</label>

          <?php if (!$themes): ?>
            <div class="text-danger">لم يتم العثور على أي ثيمات داخل <code>/assets/css/themes</code></div>
          <?php else: ?>
            <div class="row g-2">
              <?php foreach ($themes as $t):
                $checked = ($t === $__current) ? 'checked' : '';
                $id = 'theme_' . md5($t);
                $name = preg_replace('~^assets/css/themes/(theme-[^\.]+)\.css$~', '$1', $t);
              ?>
                <div class="col-12 col-md-6">
                  <label class="w-100" for="<?php echo h($id); ?>" style="cursor:pointer;">
                    <div class="p-3" style="border:1px solid var(--gdy-border);border-radius:14px;background:rgba(2,6,23,.35);display:flex;gap:10px;align-items:flex-start;">
                      <input id="<?php echo h($id); ?>" class="form-check-input" type="radio" name="site_theme" value="<?php echo h($t); ?>" style="margin-top:4px;" <?php echo $checked; ?>>
                      <div style="min-width:0;">
                        <div style="font-weight:800;"><?php echo h($name); ?></div>
                        <div class="text-muted" style="font-size:.85rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;"><?php echo h($t); ?></div>
                      </div>
                    </div>
                  </label>
                </div>
              <?php endforeach; ?>
            </div>
          <?php endif; ?>
        </div>

        <div class="d-flex gap-2">
          <button class="btn btn-primary" type="submit">حفظ</button>
          <a class="btn btn-outline-secondary" href="index.php?tab=theme">تحديث</a>
        </div>

      </form>
    </div>
  </div>
</div>
